communicate/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.urls import views as auth_views
from django.views.generic.base import RedirectView
import os 

urlpatterns = [
    path('', RedirectView.as_view(url="/auth/signup")),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('auth/',include('authentication.urls')),
    path('shares/',include('share.urls'))
]
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

share/urls.py
from django.urls import path
from . import views

app_name = 'share'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.share_create, name='share_create') ,
    path('<int:share_id>/edit/', views.share_edit, name='share_edit') ,
    path('<int:share_id>/delete/', views.share_delete, name='share_delete') ,
]

share/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

'''
    - Only a user can share a 'Share chat'
    - A share must have title
    - A share must have content
    - A share can have an image 
'''
class Share(models.Model) :
    '''
    title_max_length = 100 
    share_contents_max_length = 1000
    '''
    title_max_length = 100
    share_contents_max_length = 1000

    user = models.ForeignKey(User , on_delete=models.CASCADE)

    title = models.TextField(max_length =title_max_length, null=False, blank=False)

    share_content = models.TextField(max_length =share_contents_max_length, null=False, blank=False)

    cover_image = models.ImageField(upload_to= 'photos/', blank=True , null=True )

    created_at = models.DateTimeField(auto_now_add=True)

    updated_at = models.DateTimeField(auto_now= True)

    def __str__(self) :
        return f'{self.user.username} posted "{self.title}"'

share/forms.py
from typing import Any
from django import forms
# from django.forms.widgets import _OptAttrs
from .models import Share

class CustomClearableFile(forms.widgets.ClearableFileInput) :
    template_name = 'widgets/clearbleFileInput.html'

    def get_context(self, name: str, value: Any, attrs: dict[str, Any] | None) -> dict[str, Any]:
        
        context = super().get_context(name, value, attrs)
        return context

class ShareForm(forms.ModelForm) :
    class Meta :
        model = Share 
        fields = ['title','share_content','cover_image']
        widgets = {
            'title': forms.Textarea(attrs={
                'class': "text-input  bg-green-100 outline-none p-2 border border-transparent hover:border-green-500",
                'required': True 
                }),
            'cover_image' : CustomClearableFile(attrs={
                'class': "file-input",
                'required': False 
                }),
            'share_content': forms.Textarea(attrs={
                'class': "text-input bg-green-100 outline-none p-2 border border-transparent hover:border-green-500",
                'required': True 
                }),
        }

share/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required 

from django.http import HttpRequest,HttpResponse,HttpResponseRedirect,Http404

from .forms import ShareForm

from .models import Share

# Create your views here.

# List all shares now .
def index(request: HttpRequest) :
    shares_list = shares_list_complete()
    return render(request , 'index.html', {'shares': shares_list})

@login_required
def share_delete(request: HttpRequest , share_id) :

    share_initial = get_object_or_404(Share , pk = share_id, user = request.user)

    if request.method == 'POST' :
        share_initial.delete( )
        return redirect('share:index')
    else :
        share_new_form = ShareForm(instance=share_initial)
        return render(request , 'share_delete_confirmations.html' , { 'form' : share_new_form})

@login_required
def share_edit(request: HttpRequest , share_id) :
    share_initial = get_object_or_404(Share , pk = share_id, user = request.user)

    if request.method == 'POST' :
        share_filled_form = ShareForm(request.POST, request.FILES, instance=share_initial)
        if share_filled_form.is_valid() :
            share_form = share_filled_form.save(commit=False)
            user = request.user 
            share_form.user = user 

            share_form.save()
            return redirect('share:index')
        else :
            return redirect('share:index')
    else :
        share_new_form = ShareForm(instance=share_initial)
        return render(request , 'create_share.html' , {'form' : share_new_form})

@login_required 
def share_create(request: HttpRequest) :
    if request.method == 'POST' :
        share_filled_form = ShareForm(request.POST, request.FILES)
        if share_filled_form.is_valid() :
            share_form = share_filled_form.save(commit=False)
            user = request.user 
            share_form.user = user 

            share_form.save()
            return redirect('share:index')
        else :
            return redirect('share:index')
    else :
        share_new_form = ShareForm()
        return render(request , 'create_share.html' , {'form' : share_new_form})
    
def shares_list_complete() :
    shares_list = Share.objects.all().order_by('-created_at')
    return shares_list ;

share/templates/create_share.html
{% extends "layout.html" %} {% block content %}
<main class="w-screen h-screen flex flex-col items-center overflow-x-hidden overflow-y-auto p-16 bg-green-500" >
  <span class="flex flex-col bg-green-50 p-8 gap-8 w-[min(350px,100%)]">
    <h1 class="text-6xl text-green-800">
      {% if form.instance.pk %} Edit share {% else %} Create New Share {% endif %}
    </h1>
    <section class="flex flex-col items-center bg-green-50 gap-4">
     
      <form class="flex flex-col w-full"
        method="post"
        enctype="multipart/form-data"
      >
      <div class="flex flex-col gap-4 relative">
          {% csrf_token %} 
          {% for field in form %} 
          {% if field.label != 'Cover image' %}
          <fieldset class="flex flex-col overflow-hidden min-w-0 gap-2 relative border border-green-600 p-2">
            <label class="" for="{{ field.id_for_label }}"
              >{{field.label}}</label
            >
            <span class="overflow-auto">{{field}}</span>
          </fieldset>
          {% else %}
          <fieldset class="flex flex-col gap-2 relative p-2 border-green-500 border">
            <label class="" for="{{ field.id_for_label }}"
              >{{field.label}}</label
            >
            <span
              class="flex flex-col gap-2"
            >
              {{field}}</span
            >
          </fieldset>
          {% endif %} {% endfor %}
          <button
            class="w-full btn btn-md btn-success"
            type="submit"
          >
            Submit
          </button>
        </div>
        
      </form>

      <a
        class="link link-secondary"
        href="{% url 'share:index' %}"
        >Return to Latest shares</a
      >
    </section>
  </span>
</main>
{% endblock %}

share/templates/index.html
{% extends "layout.html" %} {% block content %}
<main class="w-screen flex flex-col overflow-x-hidden overflow-y-auto">
  <h1 class="p-4 text-6xl text-green-800">Latest</h1>
    
  <menu class="flex w-full p-4 border-b-2 border-green-950">
    <a
      href="{% url 'share:share_create' %}"
      class="btn"
    >
      Create
    </a>
  </menu>
  <section
    class="w-full grid gap-4 p-4 grid-cols-[repeat(auto-fill,minmax(240px,1fr))]"
  >
    {% for share in shares %}
    <div class="card rounded-sm glass shadow-sm flex flex-col w-full h-full">
      <figure class="h-44 overflow-hidden flex items-end justify-end">
        {% if share.cover_image %}
        <img class="" src="{{share.cover_image.url}}" alt="car!" />
        {% else %}
        <img src="" alt="No image provided" />
        {% endif %}
      </figure>
      <div class="card-body flex flex-col gap-2 p-4">
        <h2
          style="
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
          "
          class="card-title text-gray-950 text-lg/6 h-[3rem] overflow-hidden"
        >
          {{share.title}}
        </h2>
        <p
          style="
            display: -webkit-box;
            -webkit-line-clamp: 4;
            -webkit-box-orient: vertical;
          "
          class="text-gray-800 text-sm/6 h-[6rem] overflow-hidden"
        >
          {{share.share_content}}
        </p>
        <div class="card-actions justify-end text-sm/6">
          {% if user == share.user %}
          <a
            href="{% url 'share:share_edit' share.id%}"
            class="btn btn-outline bg-green-200 border-green-300 text-green-900"
            >Edit</a
          >
          <a
            href="{% url 'share:share_delete' share.id%}"
            class="btn btn-outline border-none btn-error"
            >Delete</a
          >

          {% endif %}
        </div>
      </div>
    </div>

    {% endfor %}
  </section>
</main>
{% endblock %}

share/templates/share_delete_confirmations.html
{% extends "layout.html" %} {% block content %}
<main
  class="w-screen h-screen flex flex-col items-center overflow-x-hidden overflow-y-auto p-16 bg-green-500"
>
  <span
    class="flex flex-col bg-green-50 p-8 gap-8 w-[min(450px,100%)] overflow-auto"
  >
    <h1 class="text-6xl text-green-800">Confirm deletion</h1>
    <section
      class="flex flex-col bg-green-50 border border-green-300 p-4 gap-4"
    >
      <form
        class="flex relative flex-col gap-4"
        method="post"
      >
        {% csrf_token %}
        <span class="text-xl text-green-950"
          >Are you sure to delete The
          <span class="text-green-400">Share</span></span
        >
        <fieldset class="min-w-max flex gap-4">
          <button class="btn btn-error btn-active">Delete Confirm</button>
          <a href="{% url 'share:index' %}" class="btn btn-outline">Cancel</a>
        </fieldset>
      </form>
    </section>
  </span>
</main>
{% endblock %}